<a href="https://colab.research.google.com/github/Djimdou/Side-Projects/blob/master/Ethnic_Politics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Libraries and Input

In [1]:
import pandas as pd
import plotly.express as px

# CSV file path to EPR data (stored on my GitHub)
url = "https://raw.githubusercontent.com/Djimdou/Side-Projects/master/EthnicPolitics/EPR-2021.csv"

Data Importation

In [2]:
# Read the CSV file from GitHub
df = pd.read_csv(url)

# Show first observations
df.head()

,gwid,statename,from,to,group,groupid,gwgroupid,umbrella,size,status,reg_aut
0,2,United States of America,1946,1965,Whites,1000,201000,NaN,0.6910,MONOPOLY,NaN
1,2,United States of America,1946,1965,African Americans,3000,203000,NaN,0.1240,DISCRIMINATED,False
2,2,United States of America,1946,1965,American Indians,5000,205000,NaN,0.0078,POWERLESS,True
3,2,United States of America,1966,2008,Whites,1000,201000,NaN,0.6910,DOMINANT,NaN
4,2,United States of America,1966,2008,Latinos,2000,202000,NaN,0.1250,POWERLESS,False

In [3]:
# # Chad Data

# Filter on Chad data
df_chad = df[df['statename'] == 'Chad']

 # For later graph, need to convert types of the dates
df_chad['from'] = pd.to_datetime(df_chad['from'], format='%Y', errors='coerce')
df_chad['to'] = pd.to_datetime(df_chad['to'], format='%Y', errors='coerce')


# Show firts lines
df_chad.head()

/tmp/ipython-input-3-766446254.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_chad['from'] = pd.to_datetime(df_chad['from'], format='%Y', errors='coerce')
/tmp/ipython-input-3-766446254.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_chad['to'] = pd.to_datetime(df_chad['to'], format='%Y', errors='coerce')

,gwid,statename,from,to,group,groupid,gwgroupid,umbrella,size,status,reg_aut
1782,483,Chad,1960-01-01,1975-01-01,Muslim Sahel groups,2000,48302000,NaN,0.27,POWERLESS,False
1783,483,Chad,1960-01-01,1975-01-01,Sara,4000,48304000,NaN,0.24,DOMINANT,NaN
1784,483,Chad,1960-01-01,1975-01-01,Arabs,1000,48301000,NaN,0.14,POWERLESS,False
1785,483,Chad,1960-01-01,1975-01-01,Toubou,6000,48306000,NaN,0.04,POWERLESS,False
1786,483,Chad,1976-01-01,1978-01-01,Muslim Sahel groups,2000,48302000,NaN,0.27,JUNIOR PARTNER,False

Gantt Cahrt

In [4]:
# Create a timeline (Gantt) chart

fig = px.timeline(
    df_chad,
    x_start="from",
    x_end="to",
    y="group",
    color="status",
    title="Evolution of the political status of ethnic groups in Chad",
    color_discrete_map={
        "MONOPOLY": "darkred",
        "DOMINANT": "orange",
        "SENIOR PARTNER": "gold",
        "JUNIOR PARTNER": "lightgreen",
        "POWERLESS": "lightgray",
        "DISCRIMINATED": "black",
        "SELF-EXCLUSION": "blue",
        "REGIONAL AUTONOMY": "blue"
    }
)
fig.update_yaxes(autorange="reversed")  # To make the top of the chart the top of the table
fig.show()